server:
  port: 8500
  servlet:
    context-path: /
  error:
    include-message: always


spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  # Redis
  redis:
    host: ${REDIS-HOST:localhost}
    port: ${REDIS-PORT:6379}
    password: ${REDIS-PWD:root}
    #连接超时时间（毫秒）
    timeout: 30000
  # mq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # 数据源
  datasource:
    url: jdbc:mysql://${MYSQL-HOST:localhost}:${MYSQL-PORT:3306}/${MYSQL-DB:cwl-web}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runsMillis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-timeMillis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: select 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 0
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.css,/druid/*'
      stat-view-servlet:
        enabled: true
        reset-enable: false
        login-username: ${DRUID-USER:root}
        login-password: ${DRUID-PWD:root}

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.goblincwl.cwlweb
  # 驼峰
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto

logging:
  level:
    com.goblincwl.cwlweb: debug
  file:
    name: logs/goblincw-web.log

# Actuator 开放
management:
  endpoints:
    web:
      base-path: '/manager/actuator'
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
